apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillbox
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: skillbox
        image: registry.gitlab.com/sscottie/skillbox_devops_hometask:latest
